#!/usr/bin/env ruby
#
# Copyright 2008-2010 Amazon.com, Inc. or its affiliates.  All Rights Reserved.

$LOAD_PATH.unshift File.dirname(__FILE__)

require 'amazon/datapipeline/pipelinecli'

include Amazon::DataPipeline


begin
  pipe = PipelineCLI.new(ARGV)
rescue => e
  STDERR.puts "Error: " + e.message
  exit 1
end

begin
  pipe.run
rescue => e
  STDERR.puts "Error: " + e.message
  STDERR.puts e.backtrace.join("\n")
  exit 1
end
